## ******** INTRODUCTIION ********
#### THE MAIN THING IS THAT NUMPY USES NDARRAYS WHICH IS C LANGUAGE DATA TYPE SO FOR FAST CODE EXECUTION PYTHON USE NDARRAYS DATATYPES

In [5]:
# how to import and use numpy :: 
import numpy as np 
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
# print a particular index value ::
print(a[0])

1


In [7]:
# different operations perform on array ::
a1=np.array([1,2,3])
a2=np.array([1,2,3])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1%a2)

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]
[0 0 0]


In [8]:
# different operations perform on particular index ::
print(a1[2]+a2[0]) #...etc

4


In [9]:
# two dimensional array ::
td = np.array([[1,2],[3,4],[5,6]])
print(td)

[[1 2]
 [3 4]
 [5 6]]


## ******** BASIC ARRAY OPERATIONS ********

In [10]:
print(td.ndim);print(a.ndim) # .ndim method is used to print dimesion of particular array :

2
1


In [11]:
# print item size of array ::
print(a.itemsize) # int = 4 bytes itemsize :

4


In [12]:
# print data type of array ::
print(a.dtype) # a aray has int32 data type :

int32


In [13]:
# initialize same array with different data types ::
a=np.array([1,2,3], dtype=np.float64)
print(a.itemsize) # float size is 8 bytes :

8


In [14]:
# shape method give information of array dimension ::
print(a.shape);print(td.shape)

(3,)
(3, 2)


In [17]:
# print array with default values ::
defau_zero = np.zeros((3,4))
print(defau_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
defau_ones = np.ones((3,3))
print(defau_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# create a list/array from some starting and finishing values ::
c_array = np.arange(1,5)

In [20]:
print(c_array) # don't included finishing number :

[1 2 3 4]


In [21]:
# syntax of arange : np.arange(start_index , end_index , Number_of_steps )
c_ary = np.arange(1,5,2)
print(c_ary) # work as 1,2,3,4,5 : Num_of_steps is 2 so : 1/'2'/3/'4' here 2 and 4 are not included :

[1 3]


In [22]:
# .linspace function to generate series of numbers between starting index to ending index ::
lspace = np.linspace(1,100,10) # meaning is to generate 10 numbers between 1 to 100 :
print(lspace)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [23]:
# reshape function to reshape your array ::
print(td.reshape(2,3))
print(td.reshape(1,6)) #...etc

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


In [24]:
# mathm functions ::
print(a.min()) # gives minimum value :
print(a.max()) # gives maximum value :
print(a.sum()) # gives sum of all values :

1.0
3.0
6.0


In [25]:
# if you want to apply math func of particular row or column ::
# consider td array :
print(td)
print(td.sum(axis=0)) # give the sum of all column :
print(td.sum(axis=1)) # give the sum of all rows :

[[1 2]
 [3 4]
 [5 6]]
[ 9 12]
[ 3  7 11]


In [26]:
# sqrt (square root) & std (standard deviation) function ::
sqrt = np.sqrt(16); std = np.std(a)
print(sqrt); print(std)

4.0
0.816496580927726


In [28]:
# basic mathematical operations ::
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
print(arr1+arr2) # also do many operations :

[[ 6  8]
 [10 12]]


## ******** SLICING/STACKING AND INDEXING WITH BOOLEAN ARRAYS ********

In [30]:
# slicing of one dimensional array ::
o_slc = np.array([1,2,3,4,5,6,7,8,9,10])
print(o_slc[0:6]) # print element between index 0 to 5 : 6 don't consider 
print(o_slc[-1]) # index from end starts from -1,-2.... : this will print last element :
print(o_slc[:]) # print whole array :
print(o_slc[0:]) # print 0 to end index :
print(o_slc[:10]) # print start to 9 index :

[1 2 3 4 5 6]
10
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
# slicing of two dimensional array ::
tslc = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(tslc)
print(tslc[1,2]) # it will print first(1) row and second(2):(0,1,2th) element :
print(tslc[0:2,2]) # it will go from firstly (0 to 1st row) and print second(2):(0,1,2th) element :
print(tslc[-1]) # print last row 
print(tslc[-1,0:2]) # print last row's 0th and 1st elements :
print(tslc[:,1:3]) # go throw all rows and prints 1st and 2nd column not print 0th column :

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[3 6]
[7 8 9]
[7 8]
[[2 3]
 [5 6]
 [8 9]]


In [32]:
# print whole from for loop ::
for row in tslc:
    print(row) # it will print whole array :
# .flat fucnction : if you want to flatten a array ::
for cell in tslc.flat:
    print(cell) # flatten a array :

[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


In [33]:
# verticle_stacking (.vstack) and horizontal_stacking (.hstack) function : if you want to stack/merge 2 or more arrays ::
mrg1 = np.arange(6).reshape(3,2)
mrg2 = np.arange(6,12).reshape(3,2)
merge_vertically = np.vstack((mrg1,mrg2))
merge_horizontally = np.hstack((mrg1,mrg2))
print(np.vstack(merge_vertically)) # it will merge both arrays vertically :
print(np.hstack(merge_horizontally)) # it will merge both arrays vertically :

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[ 0  1  6  7  2  3  8  9  4  5 10 11]


In [34]:
# spliting of array : horizontal_spliting (.hsplit)and verticle_spliting (.vsplit) ::
split = np.arange(30).reshape(2,15)
print(split)
hor_split = np.hsplit(split,3) # it will split array into 3 horizontal parts :
print(hor_split)
ver_split = np.vsplit(split,2) # it will split array into 3 verticle parts :
print(ver_split)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]
[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


In [35]:
# result is not perfect showing bcz of "array" written in result.
# so, we can print one by one split(part) of array :
print(hor_split[0])
print(hor_split[1])
print(hor_split[2])
print(ver_split[0])
print(ver_split[1])

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [36]:
# indexing with boolean arrays ::
ar = np.arange(12).reshape(3,4)
print(ar)
b = ar > 4 # compare all element of ar > 4 if condition is true print true else false and make a boolean array : 
print(b) # print boolean array containing true false values :
print(ar[b]) # it will print a array of true vales in b array of ar array :

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
